changelog:
  exclude:
    labels:
      - C-Meta
      - C-Release
      - C-Code-Quality
  categories:
    - title: 💥 Breaking Changes
      labels:
        - R-Breaking
    - title: ✨ New Features
      labels:
        - C-Enhancement
    - title: 🐛 Fixes
      labels:
        - C-Bug
    - title: Other Changes
      labels:
        - '*'
